image: python:3.7.5

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv sync
          - cp App.py.sample App.py
          - mkdir logs
          - pipenv install --dev pytest psutil
          - pipenv run py.test -s
