image: python:3.7.5

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv sync
          - cp App.py.sample App.py
          - cp config.json.sample config.json
          - cp logging.conf.sample logging.conf
          - mkdir logs
          - pipenv run py.test -s
